blog/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    #path('', views.index, name='index'),
    # ex: /polls/5/
    # the 'name' value as called by the {% url %} template tag
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
#django2021

import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
##    categoria = models.ForeignKey(Categoria,  on_delete=models.CASCADE)
    question_text = models.CharField("Pregunta",max_length=200)
    pub_date = models.DateTimeField('Fecha de publicación')
    def __str__(self):
        return self.question_text

    ## vista de question en admin    
    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Publicada recientemente?',
    )

#    def __str__(self):
#        return self.question_text

        ## devuelve true si la fecha es menor a 1 dia pasado (false si es anterior o futura)
    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - datetime.timedelta(days=1)

##    def has_choice(self):
##        return self.choice__isnull()

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField("Respuesta", max_length=200)
    votes = models.IntegerField("Votos", default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
##from django.template import loader
##from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.db.models import F
# utilizando F() estamos indicando al ORM de Django que obtenga el valor actual del campo y lo actualice dentro de la misma sentencia SQL.
from django.utils import timezone

from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

## se agregó filtro para q no traiga preguntas sin opciones
## y el distinct()
    def get_queryset(self):
        """Retorna las últimas 5 preguntas pubicadas.
        No toma preguntas con fecha futura"""
        return Question.objects.filter(
        pub_date__lte=timezone.now(),
        choice__isnull = False
        ).distinct().order_by('-pub_date')[:5]
        ##  __lte date filter , <= si pub_date es menor o igual a timezone.now.'''

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excluye preguntas no publicadas a la fecha y
        pregunatas sin opciones
        """
        return Question.objects.filter(pub_date__lte=timezone.now(),
        choice__isnull = False).distinct()

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """
        Excluye preguntas no publicadas a la fecha y
        pregunatas sin opciones
        """
        return Question.objects.filter(pub_date__lte=timezone.now(),
        choice__isnull = False).distinct()

##deberia filtrar las  QUESTION que no tienen choice- 404
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Vuelve a mostrar form con msg de error
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "Debe elegir una opción",
        })
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        # puede ser necesario despues de usar F() :  selected_choice.refresh_from_db()
        # Siempre  return  HttpResponseRedirect despues de guardar POST data.
        # para prevenir duplicacion si presionan Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/base_site.html
{% extends "admin/base.html" %}
{% load static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">{% endblock %}

{% block title %}{% if subtitle %}{{ subtitle }} | {% endif %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'polls:index' %}">Encuestas</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

polls/templates/polls/detail.html
{% extends "polls/base_site.html" %}
{% block content %}
<div id="content-main">

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question }}</h1>{{question.pub_date}}</legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

</div>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base_site.html" %}
{% block content %}

<div id="content-main">

<!--'''### lista de questions'''-->
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}
        </a>{{ question.pub_date }}{{asignadas_choice}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay encuestas disponibles.</p>
{% endif %}

</div>
{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base_site.html" %}
{% block content %}
<div id="content-main">

<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>
      {{ choice.choice_text }}
      -->
      {{ choice.votes }}
      voto{{ choice.votes|pluralize }}
    </li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Votar otra vez?</a>

</div>
{% endblock %}

polls/templates/polls/vote.html
<h1>{{ question.question_text }}</h1>
Usted está votando a {{ question.id }}
-
{{ question.question_text }}

<h3> Posibles respuestas</h3>
<ul>
{% for choice in question.choice_set.all %}
    <li>
      {{ choice.choice_text }}
    </li>
{% endfor %}
</ul>